### ISSUE TITLE
nouislider needs to be updated

### ISSUE THREAD

**Issue by patrickdevivo** [algolia/react-nouislider#34]
I believe a grunt task needs to be run on this package: https://www.npmjs.com/package/nouislider-algolia-fork or similar to update the `distribute/` directory of the `nouislider` so that this react wrapper can work properly.

**Comment by vvo** [comment]
@patrickdevivo unfortunately we are a bit stuck here because nouislider upgraded in ways it's not easy to upgrade for us since we are using it in instantsearch.js.

If you are looking for good sliders in the react world, I advise you to have a look at https://github.com/airbnb/rheostat or http://react-component.github.io/slider/

> so that this react wrapper can work properly.

It's not working right now?

**Comment by leongersen** [comment]
@vvo Can you be more specific about the issues in upgrading nouislider?

**Comment by adekbadek** [comment]
It looks like the algolia fork is behind the original nouislider by one version. So it's misleading to say that react-nouislider wraps nouislider while in fact it wraps a fork of it. 

The original nouislider changed how the 'connect' option works, and while the propTypes were updated by #32, the nouislider-algolia-fork is not up to date with the underlying changes in 'connect' option.

**Comment by vvo** [comment]
@leongersen Mostly the fact that nouislider went from supporting two handles to multiple handles, while we were relying on various CSS classes (like lower upper), last time I tried to migrate to new nouislider in instantsearch.js I was stuck, required a lot of work, while right now it's not necessary for us.

Ultimately what we could do is declare nouislider as a peerDependency so you can continue using it and we can use the previous version.

**Comment by leongersen** [comment]
@vvo In noUiSlider 9.1.0 (released just now), the `.noUi-handle-lower` and `.noUi-handle-upper` classes were re-added\*, and the `connect` options `'lower'` and `'upper'` are now automatically re-mapped to the new array syntax. With these changes, updating noUiSlider from 8.x to 9.x should be painless.

Could you reconsider updating this package so [people using it](https://npm-stat.com/charts.html?package=react-nouislider) can benefit from the new features and fixes in the original lib?

<sub>\* They were removed because they make less sense when you use more than two handles, but if you *do* use two handles they're useful as always.</sub>

**Comment by vvo** [comment]
@leongersen That's kind of awesome, I will put this on my TODO list and check it's ok instantsearch.js wise.

**Comment by sahaam** [comment]
Is the package is updated yet ?

**Comment by ducminhn** [comment]
It's looking like the package hasn't been updated yet, although the [nouislider ](https://github.com/leongersen/noUiSlider)has been updated on Dec 10, 2016

I'm trying to create a custom component that use the new version of nouislider. If anyone has it done, please share!

Cheers.

**Comment by vvo** [comment]
Sorry we are not maintaining this repository anymore for now. I recommend using something like https://github.com/airbnb/rheostat
